config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }

  root 'home#index'

  get '/your_keys' => 'home#keys'

  get '/a/:user_id' => 'conversations#add_friend'

  get '/c/:channel_name' => 'conversations#conversation'

  post '/k/:public_key' => 'conversations#key'

  get '/two-step' => 'authy#two_step'

  post '/confirm_code' => 'authy#confirm'

  post '/create_group/:members' => "home#create_group"

  post '/acc_pend' => "home#accept", as: :accept_pending

  get '/location/index' => 'location_sharing#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_filter :authenticate_user!
	before_filter :is_authified

	def index
		if current_user.sign_in_count == 1
			current_user.update_attributes(sign_in_count: 2)
			redirect_to '/your_keys'
		end
		@user = current_user	
		@friend_ids = []
		@friends = []
		@conversations1 = Conversation.where(u1_id: current_user.id)
		@conversations2 = Conversation.where(u2_id: current_user.id)
		@conversations1.each do |c|
			@friend_ids.push(c.u2_id)
		end
		@conversations2.each do |c|
			@friend_ids.push(c.u1_id)
		end
		@friend_ids.each do |f|
			@friends.push(User.find(f))
		end
		@group_chats = GroupChat.where(u_id: current_user.id)
		#showing pending requests
		@pending_requests = Pending.where(u2_id: current_user.id)
		@pending_friends = []
		@pending_requests.each do |pr|
			@pending_friends.push(User.find(pr.u1_id))
		end
	end
	
	def keys
		
	end

	def create_group
		names = params[:members].split("*")
		names_string = ""
		member_ids = ""
		names.each_with_index do |n, i|
			unless i == (names.length - 1)
				names_string += n + ", "
			else
				names_string += n	
			end
			member_ids += ((User.where(username: n)[0]).id).to_s
		end
		names.each do |n| 
			u = User.where(username: n)[0]
			GroupChat.create(u_id: u.id, group_id: member_ids, group_name: names_string)
		end

		render :json => {status: "created group"}
	end

	def accept
		id1 = params["id1"]
		id2 = params["id2"]
		Pending.where(u1_id: id1, u2_id: id2).destroy_all
		c1 = Conversation.new(u1_id: id1, u2_id: id2, 
			u1_pk: User.find(id1).public_key, u2_pk: User.find(id2).public_key)

		if c1.save
			redirect_to root_path, notice: "you are now friends with 
			#{User.find(id1).username}" 
		else
			redirect_to root_path, notice: "Something wrong happend"
		end
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
#subscribe_channel{style: "display: none;"}<
  = @user.username
.container_ui.clearfix
  .menu-bar.hidden-menu
    %ul
      %li
        %a#add_friend_btn{href: "#"}
          %i.fa.fa-user
          Add Friend
        %input#add_friend_input{type: "text", placeholder: "Your friend's username", autofocus: "true"}
      %li
        %a{href: "#"}
          %i.fa.fa-times
          Deactivate account
      %li
        %a{href: "/your_keys"}
          %i.fa.fa-key
          Generate new Keys
      %li
        %a#group-chat{href: "#"}
          %i.fa.fa-users
          Create group chat
        .user-dropdown
          - @friends.each do |f|
            %div{username: "#{f.username}"}
              = f.username
          %span.green-btn#create-group Create group
      %li
        = link_to destroy_user_session_path, :method => :delete do
          %i.fa.fa-sign-out
          Sign out
          
  .container_ui__heading
    .header_icon
      %i.fa.fa-envelope
    %a{href: "/"} 
      Whisper (
      = @user.username
      )
    .menu_icon
      .div
      .div
      .div
  - @friends.each_with_index do |f, i|
    %a.message{href: "/c/#{f.username}" }
      .container_ui__item
        .face
          %img{:src => "#{f.gravatar_url}"}
          - @color_num = i
          - if i > 4
            - @color_num = 0
          - @class_name = "_" + @color_num.to_s 
          .color_bar{class: "#{@class_name}"}
            %p Now Reading
            %span Read
        %h2 
          = f.username
        %h4 
          = f.status
  - if @pending_friends.length != 0
    %p.empty-container-text pending requests
    - @pending_friends.each_with_index do |f, i|
      = form_tag accept_pending_path, :method => :post do
        %button#special_button.message{type: "submit"}
          = hidden_field_tag "id1" , f.id
          = hidden_field_tag "id2" , @user.id
          .container_ui__item
            .face
              %img{:src => "#{f.gravatar_url}"}
              - @color_num = i
              - if i > 4
                - @color_num = 0
              - @class_name = "_" + @color_num.to_s 
              .color_bar{class: "#{@class_name}"}
                %p Now Reading
                %span Read
            %h2 
              = f.username
            %h4 
              = f.status
            %h3 click to accept
  - if @pending_friends.length == 0 && @friends.length == 0        
    %p.empty-container-text You haven't added any friends yet, please add friends to start chatting.
  - @group_chats.each_with_index do |g, i|
    %a.message{href: "/c/#{g.group_name}" }
      .container_ui__item
        .face
          %img{:src => "/assets/group_chat.png"}
          - @color_num = i
          - if i > 4
            - @color_num = 0
          - @class_name = "_" + @color_num.to_s 
          .color_bar{class: "#{@class_name}"}
            %p Now Reading
            %span Read
        %h2 
          = g.group_name
        %h4 
          Group Chat
:javascript
  subscribe()

app/views/home/keys.html.haml
.signup-container#keys-window{:"data-view-name" => "your_keys"}
  %h2 Your Keys
  .key#public_k YOUR_PUBLIC_KEY
  %br
  %br
  %br
  .key#private_k YOUR_PRIVATE_KEY
  %br
  %br
  .key  (keep this key safe because you will need it)
  %a#claim-key{:href => "#"} Claim Public Key